// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localUserSession,
    localDeviceContext,
    localDeviceValidation,
    localNeedleType,
    localExchangeType,
    localStorageMapping,
    localMasterDataVersion,
    localExchange,
    localExchangeEvidence,
  ];
  late final Shape0 localUserSession = Shape0(
    source: i0.VersionedTable(
      entityName: 'local_user_session',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(slot)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 localDeviceContext = Shape1(
    source: i0.VersionedTable(
      entityName: 'local_device_context',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(slot)'],
      columns: [
        _column_0,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localDeviceValidation = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_device_validation',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(slot)'],
      columns: [_column_0, _column_10, _column_24, _column_25],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 localNeedleType = Shape3(
    source: i0.VersionedTable(
      entityName: 'local_needle_type',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_26,
        _column_27,
        _column_3,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 localExchangeType = Shape4(
    source: i0.VersionedTable(
      entityName: 'local_exchange_type',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_26, _column_27, _column_3, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 localStorageMapping = Shape5(
    source: i0.VersionedTable(
      entityName: 'local_storage_mapping',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_26, _column_32, _column_33, _column_34, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 localMasterDataVersion = Shape6(
    source: i0.VersionedTable(
      entityName: 'local_master_data_version',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(collection)'],
      columns: [_column_36, _column_37],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 localExchange = Shape7(
    source: i0.VersionedTable(
      entityName: 'local_exchange',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_transaction_id)'],
      columns: [
        _column_38,
        _column_39,
        _column_10,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_9,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 localExchangeEvidence = Shape8(
    source: i0.VersionedTable(
      entityName: 'local_exchange_evidence',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_26,
        _column_38,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get slot =>
      columnsByName['slot']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get username =>
      columnsByName['username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get roles =>
      columnsByName['roles']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get permissions =>
      columnsByName['permissions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get factoryIds =>
      columnsByName['factory_ids']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locationIds =>
      columnsByName['location_ids']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get profileLoaded =>
      columnsByName['profile_loaded']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'slot',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'username',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'roles',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'permissions',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'factory_ids',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'location_ids',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'profile_loaded',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (profile_loaded IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get slot =>
      columnsByName['slot']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deviceCode =>
      columnsByName['device_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deviceName =>
      columnsByName['device_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get factoryId =>
      columnsByName['factory_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get factoryCode =>
      columnsByName['factory_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get factoryName =>
      columnsByName['factory_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get factoryTimezone =>
      columnsByName['factory_timezone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trolleyId =>
      columnsByName['trolley_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trolleyCode =>
      columnsByName['trolley_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trolleyName =>
      columnsByName['trolley_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trolleyLocationId =>
      columnsByName['trolley_location_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serverTime =>
      columnsByName['server_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get syncCursor =>
      columnsByName['sync_cursor']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'device_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'device_code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'device_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'factory_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'factory_code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'factory_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'factory_timezone',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'trolley_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'trolley_code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'trolley_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'trolley_location_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'server_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sync_cursor',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fetched_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get slot =>
      columnsByName['slot']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get checkedAt =>
      columnsByName['checked_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'checked_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get code =>
      columnsByName['code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get unit =>
      columnsByName['unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get minimumStock =>
      columnsByName['minimum_stock']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'unit',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'minimum_stock',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get code =>
      columnsByName['code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get requiresFragmentValidation =>
      columnsByName['requires_fragment_validation']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'requires_fragment_validation',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL CHECK (requires_fragment_validation IN (0, 1))',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get exchangeTypeId =>
      columnsByName['exchange_type_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get storageLocationId =>
      columnsByName['storage_location_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get storageLocationCode =>
      columnsByName['storage_location_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get storageLocationName =>
      columnsByName['storage_location_name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'exchange_type_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'storage_location_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'storage_location_code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'storage_location_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get collection =>
      columnsByName['collection']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get version =>
      columnsByName['version']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'collection',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get clientTransactionId =>
      columnsByName['client_transaction_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createIdempotencyKey =>
      columnsByName['create_idempotency_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverExchangeId =>
      columnsByName['server_exchange_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get exchangeNumber =>
      columnsByName['exchange_number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastKnownStatus =>
      columnsByName['last_known_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get operatorEmployeeNumber =>
      columnsByName['operator_employee_number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get operatorName =>
      columnsByName['operator_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'client_transaction_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'create_idempotency_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'server_exchange_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'exchange_number',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_known_status',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'operator_employee_number',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'operator_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get clientTransactionId =>
      columnsByName['client_transaction_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get evidenceType =>
      columnsByName['evidence_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get filePath =>
      columnsByName['file_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mimeType =>
      columnsByName['mime_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get byteSize =>
      columnsByName['byte_size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get capturedAt =>
      columnsByName['captured_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get idempotencyKey =>
      columnsByName['idempotency_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uploadStatus =>
      columnsByName['upload_status']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'evidence_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mime_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'byte_size',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'captured_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'idempotency_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'upload_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
